version: '3.5'
services:

  eureka-server:
    container_name: eureka-server
    image: docker12051981/service-registry:0.0.1-compose
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  config-server:
    container_name: config-server
    image: docker12051981/config-server-service:0.0.1-compose
    ports:
      - "9296:9296"
    depends_on:
      - eureka-server
    environment:
      server.port: 9296
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  gateway-service:
    container_name: gateway-service
    image: docker12051981/gateway-service:0.0.1-compose
    ports:
      - "9191:9191"
    depends_on:
      - eureka-server
      - config-server
    environment:
      server.port: 9191
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

networks: 
  default: 
    external: 
      name: microservices_spring_mongo_angular_docker_net